CLE/CLE/urls.py
from django.contrib import admin
from django.urls import path, include
from Module_TeamManagement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('Module_TeamManagement.urls','Module_TeamManagement'), namespace="TMmod")),
    path('', include(('Module_Account.urls','Module_Account'), namespace="Amod")),
    path('', include(('Module_DeploymentMonitoring.urls','Module_DeploymentMonitoring'), namespace="DMmod")),
    path('', include(('Module_EventConfig.urls','Module_EventConfig'), namespace="ECmod")),
    path('', include(('Module_CommunicationManagement.urls','Module_CommunicationManagement'), namespace="CMmod")),
]

CLE/Module_CommunicationManagement/urls.py
from django.contrib import admin
from Module_CommunicationManagement import views
from django.urls import path

urlpatterns = [
    path('instructor/TelegramManagement/',views.faculty_telegram_Base,name='faculty_telegram_Base'),
    path('instructor/TelegramManagement/update/chat_members/',views.faculty_telegram_UpdateChatMembers,name='faculty_telegram_UpdateChatMembers'),
    path('instructor/TelegramManagement/create/group/',views.faculty_telegram_CreateGroup,name='faculty_telegram_CreateGroup'),
    path('instructor/TelegramManagement/create/channel/',views.faculty_telegram_CreateChannel,name='faculty_telegram_CreateChannel'),
    path('instructor/TelegramManagement/delete/chat/',views.faculty_telegram_DeleteChat,name='faculty_telegram_DeleteChat'),
    path('instructor/TelegramManagement/sendMessage/',views.faculty_telegram_SendMessage,name='faculty_telegram_SendMessage'),
    path('instructor/TelegramManagement/getChatLink/',views.faculty_telegram_GetChatLink,name='faculty_telegram_GetChatLink'),
]

CLE/Module_DeploymentMonitoring/urls.py
from django.contrib import admin
from Module_DeploymentMonitoring import views
from django.urls import path,re_path

urlpatterns = [
    path('instructor/ITOperationsLab/setup/awskeys/',views.faculty_Setup_GetAWSKeys,name='itopslab_setup_AWSKeys'),
    path('instructor/ITOperationsLab/monitor/',views.faculty_Monitor_Base,name='itopslab_monitor'),
    path('student/ITOperationsLab/deploy/',views.student_Deploy_Base,name='itopslab_studeploy'),
    path('student/ITOperationsLab/deploy/<str:course_title>/2',views.student_Deploy_Upload,name='itopslab_studeployUpload'),
    path('student/ITOperationsLab/monitor/',views.student_Monitor_Base,name='itopslab_stumonitor'),

    # For adding deployment packages into system
    path('instructor/ITOperationsLab/setup/deployment_package/',views.faculty_Setup_GetGitHubLinks,name='dp_list'),
    path('instructor/ITOperationsLab/setup/deployment_package/create/', views.faculty_Setup_AddGitHubLinks, name='dp_create'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/<str:pk>/update/', views.faculty_Setup_UpdateGitHubLinks, name='dp_update'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/<str:pk>/delete/', views.faculty_Setup_DeleteGitHubLinks, name='dp_delete'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/delete/all/', views.faculty_Setup_DeleteAllGitHubLinks, name='dp_delete_all'),

    # For retrieving and sharing of AMI
    path('instructor/ITOperationsLab/setup/',views.faculty_Setup_Base,name='itopslab_setup'),
    path('instructor/ITOperationsLab/setup/ami/get/',views.faculty_Setup_GetAMI,name='itopslab_setup_AMI_get'),
    path('instructor/ITOperationsLab/setup/ami/accounts/get/',views.faculty_Setup_GetAMIAccounts,name='itopslab_setup_AMI_Accounts_get'),
    path('instructor/ITOperationsLab/setup/ami/accounts/share/',views.faculty_Setup_ShareAMI,name='itopslab_setup_AMI_Accounts_share'),

    # For standard student deployment page
    path('student/ITOperationsLab/deploy/standard/',views.student_Deploy_Standard_Base,name='itopslab_studeploy_standard'),
    path('student/ITOperationsLab/deploy/standard/deployment_package/',views.student_Deploy_Standard_GetDeploymentPackages,name='dp_list_student'),
    path('student/ITOperationsLab/deploy/standard/account/',views.student_Deploy_Standard_AddAccount,name='itopslab_studeploy_standard_AddAccount'),
    path('student/ITOperationsLab/deploy/standard/server/',views.student_Deploy_Standard_GetIPs,name='server_list'),
    path('student/ITOperationsLab/deploy/standard/server/create/',views.student_Deploy_Standard_AddIPs,name='server_create'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/<str:pk>/update/',views.student_Deploy_Standard_UpdateIPs,name='server_update'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/<str:pk>/delete/',views.student_Deploy_Standard_DeleteIPs,name='server_delete'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/delete/all/',views.student_Deploy_Standard_DeleteAllIPs,name='server_delete_all'),
]

CLE/Module_EventConfig/urls.py
from django.contrib import admin
from Module_EventConfig import views
from django.urls import path,re_path

urlpatterns = [
    path('background_tasks/test/',views.test,name='test'),
    path('instructor/ITOperationsLab/event/',views.faculty_Event_Base,name='itopslab_event'),
    path('instructor/ITOperationsLab/event/get/servers/',views.faculty_Event_GetServers,name='faculty_Event_GetServers'),
    path('instructor/ITOperationsLab/event/execute/',views.faculty_Event_Execute,name='itopslab_event_execute'),
    path('event/start/', views.serverCall), #Temp endpoint
    path('event/recovery/', views.serverRecoveryCall),

    # For events logs
    path('instructor/ITOperationsLab/eventslog/',views.events_list,name='events_list'),
    path('instructor/ITOperationsLab/eventslog/<str:pk>/update/', views.events_update, name='events_update'),
    path('instructor/ITOperationsLab/eventslog/<str:pk>/delete/', views.events_delete, name='events_delete'),
]

CLE/Module_TeamManagement/urls.py
from Module_TeamManagement import views
from django.contrib import admin
from django.urls import path
from Module_TeamManagement.forms import PhoneNumberForm, VerificationCodeForm,TrailheadForm
from Module_TeamManagement.views import TelegramWizard, PhoneNumberFormView

urlpatterns = [
    path('home/', views.home, name='home'),
    path('home/aboutCloudtopus/', views.aboutCloudtopus, name='aboutCloudtopus'),
    path('student/configTools/', views.configureDB_clt, name='uploadtoolStudent'),
    path('instructor/configTools/', views.configureDB_clt, name='uploadtools'),
    path('instructor/configStudents/', views.configureDB_course, name='uploadcsv'),
    path('instructor/configTeams/', views.configureDB_teams, name='uploadteam'),
    path('student/team/', views.student_Team, name='sTeam'),
    path('student/stats/', views.student_Stats, name='sStats'),
    path('instructor/overview/', views.faculty_Overview, name='instOverview'),
    path('instructor/home/', views.faculty_Dashboard, name='instHome'),
    path('instructor/home2/', views.faculty_HomePage, name='instHome2'),
    path('CLEAdmin/',views.CLEAdmin, name = 'cleAdmin'),
    path('CLEAdmin/moduleSetup',views.configureDB_faculty, name = 'modSu'),
    path('charts/',views.line_chart, name = 'charts_view'),
    # path('instructor/telegram_setup/', TelegramWizard.as_view(FORMS, condition_dict={'verificationcode': views.enter_phonenumber}), name='telegram_setup'),
    # path('instructor/telegram_setup/', TelegramWizard.as_view([PhoneNumberForm, VerificationCodeForm]), name='telegram_setup'),
    path('instructor/telegram_setup/', views.configureDB_telegram, name='telegram_setup'),
    path('join/', PhoneNumberFormView.as_view(), name='phone_number_form'),
    path('csv/clt_file', views.clt_file_download),
    path('admin/csv/clt_file.csv', views.clt_file_ouput, name = "clt_file"),
    path('celery/trailhead/refresh', views.trailhead_refresh, name = 'trailhead_refresh'),
    #trailmixes
    path('instructor/trailmix/',views.trailhead_list,name='trailhead_list'),
    path('instructor/trailmix/create/', views.trailhead_create, name='trailhead_create'),
    path('instructor/trailmix/<str:pk>/delete/', views.trailhead_delete, name='trailhead_delete'),
]

CLE/Module_TeamManagement/models.py
from django.db import models
from Module_DeploymentMonitoring.models import AWS_Credentials

class Course(models.Model):
    course_title = models.CharField(
        db_column='Course_Title',
        max_length=255,
        primary_key=True,
    )
    course_name = models.CharField(
        db_column='Course_Name',
        max_length=255,
    )
    course_description = models.TextField(
        db_column='Course_Description',
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Course'

class Student(models.Model):
    email = models.EmailField(
        db_column='Student_Email',
        primary_key=True,
    )
    username = models.CharField(
        db_column='Username',
        max_length=255,
    )
    firstname = models.CharField(
        db_column='Firstname',
        max_length=255,
    )
    lastname = models.CharField(
        db_column='Lastname',
        max_length=255,
    )
    telegram_username = models.CharField(
        db_column='Student_Telegram_Username',
        max_length=255,
        null=True,
    )
    loginCounts = models.IntegerField(
        db_column='Number_of_Logins',
        default=0,
    )

    class Meta:
        managed = True
        db_table = 'Student'

class Course_Section(models.Model):
    course_section_id = models.CharField(
        db_column='Course_Section_ID',
        max_length=255,
        primary_key=True,
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        db_column='Course',
    )
    section_number = models.CharField(
        db_column='Section_Number',
        max_length=2,
    )
    teaching_assistant = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        db_column='Teaching_Assistant',
        null=True,
    )

    learning_tools = models.TextField(
        db_column='Course_Section_Learning_Tools_List',
        null=True,
    )
    to_string = models.CharField(
        db_column='To_String',
        max_length=255,
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Course_Section'
        unique_together = (('course','section_number'),('course', 'teaching_assistant'))

class Faculty(models.Model):
    email = models.EmailField(
        db_column='Faculty_Email',
        primary_key=True,
    )
    username = models.CharField(
        db_column='Username',
        max_length=255,
    )
    firstname = models.CharField(
        db_column='Firstname',
        max_length=255,
    )
    lastname = models.CharField(
        db_column='Lastname',
        max_length=255,
    )
    phone_number = models.CharField(
        db_column='Phone_Number',
        max_length=255,
        null=True,
    )
    telegram_username = models.CharField(
        db_column='Faculty_Telegram_Username',
        max_length=255,
        null=True,
    )
    course_section = models.ManyToManyField(
        Course_Section,
        db_column='Course_Section',
        null=True,
    )
    awscredential = models.ForeignKey(
        AWS_Credentials,
        on_delete=models.CASCADE,
        db_column='AWS_Credentials',
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Faculty'

class Cloud_Learning_Tools(models.Model):
    id = models.CharField(
        db_column='ID',
        max_length=255,
        primary_key=True,
    )
    type = models.CharField(
        db_column='Type',
        max_length=255,
    )
    website_link = models.TextField(
        db_column='Website_Link',
    )
    course_section = models.ManyToManyField(Course_Section)
    class Meta:
        managed = True
        db_table = 'Cloud_Learning_Tools'

class School_Term(models.Model):
    school_term_id = models.CharField(
        db_column='School_Term_ID',
        max_length=255,
        primary_key=True,
    )
    term = models.CharField(
        db_column='Term',
        max_length=255,
    )
    financial_year = models.CharField(
        db_column='Financial_Year',
        max_length=255,
    )
    start_date = models.DateField(
        db_column='Start_Date',
    )
    end_date = models.DateField(
        db_column='End_Date',
    )

    class Meta:
        managed = True
        db_table = 'School_Term'
        unique_together = (('financial_year','term'),)

class Telegram_Chats(models.Model):
    CHAT_TYPE = (
        ('Channel','Channel'),
        ('Group','Group'),
    )

    id = models.AutoField(
        db_column='ID',
        primary_key=True,
    )
    name = models.CharField(
        db_column='Name',
        max_length=255,
    )
    type = models.CharField(
        db_column='Type',
        max_length=10,
        choices=CHAT_TYPE,
    )
    link = models.TextField(
        db_column='Link',
        null=True,
    )
    members = models.TextField(
        db_column='Members',
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Telegram_Chats'

class Class(models.Model):
    school_term = models.ForeignKey(
        School_Term,
        on_delete=models.CASCADE,
        db_column='School_Term',
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        db_column='Student',
    )
    team_number = models.CharField(
        db_column='Team_Number',
        max_length=255,
        null=True,
    )
    course_section = models.ForeignKey(
        Course_Section,
        on_delete=models.CASCADE,
        db_column='Course_Section',
    )
    awscredential = models.ForeignKey(
        AWS_Credentials,
        on_delete=models.CASCADE,
        db_column='AWS_Credentials',
        null=True,
    )
    clt_id = models.ManyToManyField(
        Cloud_Learning_Tools,
        db_column='CLT_ID',
        null=True,
    )
    telegram_chats = models.ManyToManyField(
        Telegram_Chats,
        db_column='Telegram_Chats',
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Class'
        unique_together = (('student','course_section','school_term'),)

class Trailmix_Information(models.Model):
    name = models.CharField(
        db_column='Name',
        max_length=255,
        null= True,
    )
    link = models.TextField(
        db_column='Link',
        null=True,
    )
    description = models.TextField(
        db_column='Description',
        null=True,
    )
    badges = models.TextField(
        db_column='Badges',
        null=True,
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        db_column='Course',
        null=True,
    )
    course_sections = models.TextField(
        db_column='Course_Sections_Details',
        null=True,
    )

    class Meta:
        managed = True
        db_table = 'Trailmix_Information'

CLE/Module_TeamManagement/forms.py
from django import forms
from Module_TeamManagement.models import *

class TrailheadForm(forms.ModelForm):
    class Meta:
        model = Trailmix_Information
        fields = ( 'link','course', )

# class InstructorToolsForm(forms.Form):
#     tools = forms.ChoiceField(choices=[('Trailhead','Tableau','Kahoot')])

class PhoneNumberForm(forms.Form):
    phone_number = forms.CharField(max_length=8)

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if len(phone_number) != 8:
            raise forms.ValidationError("This is not a valid number")
        return phone_number

class VerificationCodeForm(forms.Form):
    login_code = forms.CharField(max_length=6)

CLE/templates/Module_TeamManagement/Instructor/ITOpsLabSetup.html
{% extends 'Module_TeamManagement/Instructor/instructorBase.html' %}
{% load staticfiles %}

{% block bootstrapContent %}
<head>
    <link rel="stylesheet" href="{% static 'css/itopssetup.css' %}">

</head>

<div class="col-md-12">
    <img src="{% static 'images/ITOpsLab Header.png' %}" alt="Devops" width=370px height = 180px style="display: block;margin-left: auto;margin-right: auto;"><br>

    <h2 class = "text-center"> {{ course_title }} </h2>
    <div class= "redirect">
        <div class="btn-group col-md-8 text-center" style="display: block;margin-left: auto;margin-right: auto;">
          <button onclick="location.href= '{% url 'DMmod:itopslab_setup' %}?course_title={{course_title}}';" type="button" class="btn btn-dark active" >Setup</button>
          <button onclick="location.href = '{% url 'DMmod:itopslab_monitor' %}?course_title={{course_title}}&section_number={{first_section}}';" type="button" class="btn btn-dark">Monitor</button>
          <button onclick="location.href = '{% url 'ECmod:itopslab_event' %}?course_title={{course_title}}';" type="button" class="btn btn-dark">Event Management</button>
        </div>
    </div>

    <hr>
    <div class="itopsheader">SETUP</div>
    <br>
    <div id="accordion" class="panel-group col-md-9" style="display: block;margin-left: auto;margin-right: auto;">
        <div class="panel">
        <div class="panel-heading">
        <h5 class="panel-title">
            <a href="#panelBodyOne" class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion">AWS Information</a>
            </h5>
        </div>

         <!-- Request AWS Information-->
        <div id="panelBodyOne" class="panel-collapse collapse">
            <div class="panel-body">

                <form id="awsinfo" action="{% url 'DMmod:itopslab_setup_AWSKeys' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                    {% csrf_token %}
                    <div class="container col-md-6" style="display: block;margin-left: auto;margin-right: auto;">
                        <label for="name" class="control-label">Account Number</label>
                        <input class="form-control" type="text" name="account_number" id="account_number" aria-describedby="fileHelp" placeholder="Account Number">
                        <br>
                        <label for="name" class="control-label">AWS Access Key</label>
                        <input class="form-control" type="text" name="access_key" id="access_key" aria-describedby="fileHelp" placeholder="AWS Access Key">
                        <br>
                        <label for="name" class="control-label">AWS Secret Access Key</label>
                        <input class="form-control" type="text" name="secret_access_key" id="secret_access_key" aria-describedby="fileHelp" placeholder="AWS Secret Access Key">
                    </div>
                    <div class="col-md-9 form-group" style = "margin-bottom:40px;">
                        <br>
                        <button class="btn btn-dark pull-right" type="submit" value="Submit">Submit</button>
                        <input type="hidden" name="course_title" id="course_title" value={{course_title}}>
                    </div>
                </form>
                <div class="container col-md-9" style="display: block;margin-left: auto;margin-right: auto;">
                    <h5><b>Submitted Account Number</b>
                    {% if account_number != "" %}
                        <b>Current Account Number:</b> {{account_number}}
                    {% else %}
                        <div class ="error">No Account Number submitted</div>
                    {%endif %}

                    <h5><b>Submitted AWS Access Key</b>
                    {% if access_key != "" %}
                        <b>Current AWS Access Key:</b> {{access_key}}
                    {% else %}
                        <div class ="error">No AWS Access Key submitted</div>
                    {%endif %}

                    <h5><b>Submitted Secret Access Key</b>
                    {% if secret_access_key != "" %}
                        <b>Current Secret Access Key:</b> {{secret_access_key}}
                    {% else %}
                        <div class ="error">No Secret Access Key submitted</div>
                    {%endif %}
                </div>

            </div>
        </div>
        </div>

        <div class="panel">
        <div class="panel-heading">
        <h5 class="panel-title">
            <a href="#panelBodyTwo" class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion">Deployment Package</a>
            </h5>
        </div>
         <!-- Deployment Package Table-->
        <div id="panelBodyTwo" class="panel-collapse collapse">
        <div class="panel-body">
            <div class="container col-md-12" style="display: block;margin-left: auto;margin-right: auto;">
            {% include "dataforms/deploymentpackage/dp_list.html" %}
          </div>
            </div>
        </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
            <h5 class="panel-title">
                <a href="#panelBodyThree" class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion">Approve & Send Image</a>
                </h5>
            </div>
         <!-- Approve and Send Image Steps-->
            <div id="panelBodyThree" class="panel-collapse collapse">
                <div class="panel-body">

                {% include 'Module_TeamManagement/Instructor/ITOpsSetupForm.html' %}

                </div>
            </div>
        </div>
    </div>

{% include 'popupmessages/message.html' %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js" type="text/javascript"></script>
    <script>
        //validations for form fields
        $("#awsinfo").validate({
            rules: {
                account_number: {
                    digits: true, //checks account number if digits have been entered
                    required: true
                },
                access_key: {
                    required: true
                },
                secret_access_key: {
                    required: true
                }
            },
            messages: {
                account_number: {
                    digits: "Please enter a valid AWS Account Number.",
                    required: "Please enter your AWS Account Number."
                },
                access_key: {
                    required: "Please enter your AWS Access Key."
                },
                secret_access_key: {
                    required: "Please enter your AWS Secret Access Key."
                }
            }
        });
        // var isClosed = true;
        // var toggle = document.getElementById("accordion-toggle");
        // var panel = document.getElementById("panelBodyOne")
        // console.log(toggle);
        // toggle.addEventListener("click", function() {
        //     toggle.classList.add("collapsed");
        //     panel.classList.remove("in");
        //     panel.classList.remove("show");
        //     console.log("heyo");
        // })
        // $(function(){
        // var accNum = "{{submittedAccNum}}";
        // var accKey =  "{{submittedAccKey}}";
        // var secKey = "{{submittedSecKey}}";

        //     if (accNum!=""){
        //         document.forms['awsinfo'].elements['email'].value = accNum;
        //     }
        //     if (accKey!=""){
        //         document.forms['awsinfo'].elements['accessKey'].value = accKey;
        //     }
        //     if (secKey!=""){
        //         document.forms['awsinfo'].elements['secretKey'].value = secKey;
        //     }
        // });

        // $( document ).ready(function() {
        // // after the page elements are all loaded, then run the script
        // // Set the input field with unique ID #email to a value

        // $("#email").val('someone@test.com');

        // // Set the input field with unique ID #name

        // $("#name").val('John Doe');

        // });
        $("#checkAll").click(function () {
          $('input:checkbox').not(this).prop('checked', this.checked);
        });
    </script>

    <!--to remove after UT!-->
    <!-- <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    </script> -->
<!--to remove after UT!-->

{% endblock %}

CLE/templates/Module_TeamManagement/Instructor/instructorBase.html
{% extends 'Module_TeamManagement/dashboardbase.html' %}
{% load staticfiles %}

{% block title %}
Instructor page
{% endblock %}

{% block sideuserprofile %}
<div class="col-md-12">
    <div class="cardsidebar card-user">
        <div class="card-image">
        </div>
            <div class="author">
                <img class="avatar border-gray" src="{{ request.session.user_picture }}" alt="...">
                <h5 class="title">{{ request.session.user_name }}</h5>
                <p class="description">Faculty</p>
            </div>
        <hr>
    </div>
</div>
{% endblock %}

{% block sidenavBar %}
<li class="nav-item {{ home2 }}">
    <a class="nav-link" href="{% url 'TMmod:instHome2' %}">
        <i class="fas fa-home"></i>
        <p>Home</p>
    </a>
</li>

<li class="nav-item {{ faculty_Home }}">
    <a class="nav-link" href="{% url 'TMmod:instHome' %}">
        <i class="fas fa-chart-pie"></i>
        <p>Dashboard</p>
    </a>
</li>

<div id="accordion">
<li class="nav-item {{ faculty_Overview }}">
    <a class="nav-link" href ="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <i class="fas fa-users"></i>
        <span class="no-icon">Student Mgmt</span>
    </a>
</li>
    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" aria-expanded="true" data-parent="#accordion">
        {% for course_title,course_sectionList in request.session.courseList_updated.items %}
            <a class="nav-link" href="{% url 'TMmod:instOverview' %}?module={{ course_sectionList.0.id }}&course_title={{ course_title }}&section_number={{ course_sectionList.0.section_number }}">
                <p class="col-md-3 col-sm-3 col-xs-12 control-label">{{ course_title }}</p>
            </a>
        {% endfor %}
    </div>
</div>

<li class="nav-item {{ configureDB_course }}">
    <a class="nav-link" href="{% url 'TMmod:uploadcsv' %}">
      <i class="fas fa-chalkboard-teacher"></i>
      <p>Course Mgmt</p>
    </a>
</li>

{% for tool in request.session.configured_Tools %}
    {% if tool == 'ITOpsLab' %}
    <div id="accordion">
        <li class="nav-item {{ ITOpsLabSetup }}">
            <a class="nav-link" href ="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              <i class="fas fa-infinity"></i>
              <span class="no-icon">IT Ops Lab</span>
            </a>
        </li>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" aria-expanded="true" data-parent="#accordion">
            {% for course_title,course_sectionList in request.session.courseList_ITOpsLab.items %}
                <a class="nav-link" href="{% url 'DMmod:itopslab_setup' %}?course_title={{ course_sectionList.0.course_title }}">
                    <p class="col-md-3 col-sm-3 col-xs-12 control-label">{{ course_title }}</p>
                </a>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endfor %}

{% for tool in request.session.configured_Tools %}
    {% if tool == 'Telegram' %}
        <div id="accordion">
            <li class="nav-item {{ faculty_telegram_Base }}">
                <a class="nav-link" href ="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <i class="fab fa-telegram"></i>
                    <span class="no-icon">Telegram Mgmt</span>
                </a>
            </li>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" aria-expanded="true" data-parent="#accordion">
                    {% for course_title,course_sectionList in request.session.courseList_updated.items %}
                        <a class="nav-link" href="{% url 'CMmod:faculty_telegram_Base' %}?course_section={{ course_sectionList.0.id }}">
                            <p class="col-md-3 col-sm-3 col-xs-12 control-label">{{ course_title }}</p>
                        </a>
                    {% endfor %}
                </div>
        </div>
    {% endif %}
{% endfor %}

{% endblock %}

CLE/templates/Module_TeamManagement/Instructor/instructorTrailmixes.html
{% extends 'Module_TeamManagement/Instructor/instructorBase.html' %}

{% block TrailmixContent %}
<div class="redirect">
    <span>
      <button onclick="location.href= '{% url 'TMmod:uploadcsv' %}';" type="button" class="btn btn-dark">Course Setup</button>
      <button onclick="location.href = '{% url 'TMmod:uploadteam' %}';" type="button" class="btn btn-dark">Teams Setup</button>
      <button onclick="location.href = '{% url 'TMmod:uploadtools' %}?user=faculty';" type="button" class="btn btn-dark active">Tools Setup</button>
    </span>
<div>


<div class="col-md-12">
<h1>Trailmix Setup</h1>
{% include "dataforms/trailmixes/trailhead_list.html" %}
</div>
{% endblock %}