CLE/CLE/urls.py
from django.contrib import admin
from django.urls import path, include
from Module_TeamManagement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('Module_TeamManagement.urls','Module_TeamManagement'), namespace="TMmod")),
    path('', include(('Module_Account.urls','Module_Account'), namespace="Amod")),
    path('', include(('Module_DeploymentMonitoring.urls','Module_DeploymentMonitoring'), namespace="DMmod")),
    path('', include(('Module_EventConfig.urls','Module_EventConfig'), namespace="ECmod")),
    path('', include(('Module_CommunicationManagement.urls','Module_CommunicationManagement'), namespace="CMmod")),
]

CLE/Module_DeploymentMonitoring/urls.py
from django.contrib import admin
from Module_DeploymentMonitoring import views
from django.urls import path,re_path

urlpatterns = [
    path('instructor/ITOperationsLab/setup/awskeys/',views.faculty_Setup_GetAWSKeys,name='itopslab_setup_AWSKeys'),
    path('instructor/ITOperationsLab/monitor/',views.faculty_Monitor_Base,name='itopslab_monitor'),
    path('student/ITOperationsLab/deploy/',views.student_Deploy_Base,name='itopslab_studeploy'),
    path('student/ITOperationsLab/deploy/<str:course_title>/2',views.student_Deploy_Upload,name='itopslab_studeployUpload'),
    path('student/ITOperationsLab/monitor/',views.student_Monitor_Base,name='itopslab_stumonitor'),

    # For adding deployment packages into system
    path('instructor/ITOperationsLab/setup/deployment_package/',views.faculty_Setup_GetGitHubLinks,name='dp_list'),
    path('instructor/ITOperationsLab/setup/deployment_package/create/', views.faculty_Setup_AddGitHubLinks, name='dp_create'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/<str:pk>/update/', views.faculty_Setup_UpdateGitHubLinks, name='dp_update'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/<str:pk>/delete/', views.faculty_Setup_DeleteGitHubLinks, name='dp_delete'),
    path('instructor/ITOperationsLab/setup/deployment_package/<str:course_title>/delete/all/', views.faculty_Setup_DeleteAllGitHubLinks, name='dp_delete_all'),

    # For retrieving and sharing of AMI
    path('instructor/ITOperationsLab/setup/',views.faculty_Setup_Base,name='itopslab_setup'),
    path('instructor/ITOperationsLab/setup/ami/get/',views.faculty_Setup_GetAMI,name='itopslab_setup_AMI_get'),
    path('instructor/ITOperationsLab/setup/ami/accounts/get/',views.faculty_Setup_GetAMIAccounts,name='itopslab_setup_AMI_Accounts_get'),
    path('instructor/ITOperationsLab/setup/ami/accounts/share/',views.faculty_Setup_ShareAMI,name='itopslab_setup_AMI_Accounts_share'),

    # For standard student deployment page
    path('student/ITOperationsLab/deploy/standard/',views.student_Deploy_Standard_Base,name='itopslab_studeploy_standard'),
    path('student/ITOperationsLab/deploy/standard/deployment_package/',views.student_Deploy_Standard_GetDeploymentPackages,name='dp_list_student'),
    path('student/ITOperationsLab/deploy/standard/account/',views.student_Deploy_Standard_AddAccount,name='itopslab_studeploy_standard_AddAccount'),
    path('student/ITOperationsLab/deploy/standard/server/',views.student_Deploy_Standard_GetIPs,name='server_list'),
    path('student/ITOperationsLab/deploy/standard/server/create/',views.student_Deploy_Standard_AddIPs,name='server_create'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/<str:pk>/update/',views.student_Deploy_Standard_UpdateIPs,name='server_update'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/<str:pk>/delete/',views.student_Deploy_Standard_DeleteIPs,name='server_delete'),
    path('student/ITOperationsLab/deploy/standard/server/<str:course_title>/delete/all/',views.student_Deploy_Standard_DeleteAllIPs,name='server_delete_all'),
]

CLE/templates/dataforms/serverdetails/partial_server_create.html
<form method="post" action="{% url 'DMmod:server_create' %}" class="js-server-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Add a new Server</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'dataforms/serverdetails/partial_server_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary" onclick="enableButton()">Add Server</button>
    <input type="hidden" name="course_title" id="course_title" value={{course_title}}>
  </div>
</form>

<script>
    function enableButton(){
        document.getElementById("delete_all_servers").disabled = false;
    };
</script>

CLE/templates/dataforms/serverdetails/partial_server_delete.html
<form method="post" action="{% url 'DMmod:server_delete' course_title=course_title pk=server.IP_address %}" class="js-server-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm Server deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the server: <strong>{{ server.IP_address }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger" onclick="disableButton()">Delete Server</button>
    <input type="hidden" name="course_title" id="course_title" value={{course_title}}>
  </div>
</form>

<script>
    function disableButton(){
        document.getElementById("delete_all_servers").disabled = true;
    };
</script>

CLE/templates/dataforms/serverdetails/partial_server_delete_all.html
<form method="post" action="{% url 'DMmod:server_delete_all' course_title=course_title %}" class="js-server-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm Servers deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete <strong>ALL</strong> the servers? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger" onclick="disableButton()">Delete All Servers</button>
    <input type="hidden" name="course_title" id="course_title" value={{course_title}}>
  </div>
</form>

<script>
    function disableButton(){
        document.getElementById("delete_all_servers").disabled = true;
    };
</script>

CLE/templates/dataforms/serverdetails/partial_server_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

CLE/templates/dataforms/serverdetails/partial_server_list.html
{% for server in servers %}
  <tr>
      <td>{{ server.server_ip }}</td>
      <td>{{ server.server_id }}</td>
      <td>{{ server.server_name }}</td>
      <td>{{ server.server_type }}</td>
    <td style="width: 250px">
      <button type="button"
              class="btn btn-warning btn-sm js-update-server"
              data-url="{% url 'DMmod:server_update' pk=server.server_ip course_title=course_title %}?course_title={{course_title}}">
          <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-server"
              data-url="{% url 'DMmod:server_delete' pk=server.server_ip course_title=course_title %}?course_title={{course_title}}">
          <span class="glyphicon glyphicon-trash"></span> Delete
     </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No servers</td>
  </tr>
{% endfor %}

CLE/templates/dataforms/serverdetails/partial_server_update.html
<form method="post" action="{% url 'DMmod:server_update' course_title form.instance.pk %}" class="js-server-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Update Server</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'dataforms/serverdetails/partial_server_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update server</button>
    <input type="hidden" name="course_title" id="course_title" value={{course_title}}>
  </div>
</form>

CLE/templates/dataforms/serverdetails/server_list.html
{% extends 'dataforms/dataformbase.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'js/dataforms/server.js' %}"></script>
{% endblock %}

{% block content %}
  <!-- BUTTON TO TRIGGER THE ACTION -->
  <p>
      <button type="button" class="btn btn-primary js-create-server"data-url="{% url 'DMmod:server_create' %}?course_title={{course_title}}">
          <span class="glyphicon glyphicon-plus"></span> New Server
      </button>
      <button id="delete_all_servers" type="button" class="btn btn-danger js-create-server" data-url="{% url 'DMmod:server_delete_all' course_title=course_title %}?course_title={{course_title}}">
          <span class="glyphicon glyphicon-plus"></span> Delete All Servers
      </button>
  </p>

  <table class="table" id="server-table">
    <thead>
      <tr>
        <th>Server IP</th>
        <th>Server ID</th>
        <th>Server Name</th>
        <th>Server Type</th>
      </tr>
    </thead>
    <tbody>
        {% include 'dataforms/serverdetails/partial_server_list.html' %}
    </tbody>
  </table>

  <!-- THE MODAL WE WILL BE USING -->
 <div class="modal fade" id="modal-server" data-backdrop="static"  data-keyboard="false">
   <div class="modal-dialog">
     <div class="modal-content">
     </div>
   </div>

<script>
    $(document).ready(function() {
      console.log("{% url 'DMmod:itopslab_studeploy_standard' %}server/?course_title={{course_title}} #server-table");
      $("#server-table").load("{% url 'DMmod:itopslab_studeploy_standard' %}server/?course_title={{course_title}} #server-table");

      var servers_count = "{{servers_count}}";
      if(servers_count == 0){
          document.getElementById("delete_all_servers").disabled = true;
      };
    });
</script>
{% endblock %}