CLE/CLE/urls.py
from django.contrib import admin
from django.urls import path, include
from Module_TeamManagement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('Module_TeamManagement.urls','Module_TeamManagement'), namespace="TMmod")),
    path('', include(('Module_Account.urls','Module_Account'), namespace="Amod")),
    path('', include(('Module_DeploymentMonitoring.urls','Module_DeploymentMonitoring'), namespace="DMmod")),
    path('', include(('Module_EventConfig.urls','Module_EventConfig'), namespace="ECmod")),
    path('', include(('Module_CommunicationManagement.urls','Module_CommunicationManagement'), namespace="CMmod")),
]

CLE/Module_TeamManagement/urls.py
from Module_TeamManagement import views
from django.contrib import admin
from django.urls import path
from Module_TeamManagement.forms import PhoneNumberForm, VerificationCodeForm,TrailheadForm
from Module_TeamManagement.views import TelegramWizard, PhoneNumberFormView

urlpatterns = [
    path('home/', views.home, name='home'),
    path('home/aboutCloudtopus/', views.aboutCloudtopus, name='aboutCloudtopus'),
    path('student/configTools/', views.configureDB_clt, name='uploadtoolStudent'),
    path('instructor/configTools/', views.configureDB_clt, name='uploadtools'),
    path('instructor/configStudents/', views.configureDB_course, name='uploadcsv'),
    path('instructor/configTeams/', views.configureDB_teams, name='uploadteam'),
    path('student/team/', views.student_Team, name='sTeam'),
    path('student/stats/', views.student_Stats, name='sStats'),
    path('instructor/overview/', views.faculty_Overview, name='instOverview'),
    path('instructor/home/', views.faculty_Dashboard, name='instHome'),
    path('instructor/home2/', views.faculty_HomePage, name='instHome2'),
    path('CLEAdmin/',views.CLEAdmin, name = 'cleAdmin'),
    path('CLEAdmin/moduleSetup',views.configureDB_faculty, name = 'modSu'),
    path('charts/',views.line_chart, name = 'charts_view'),
    # path('instructor/telegram_setup/', TelegramWizard.as_view(FORMS, condition_dict={'verificationcode': views.enter_phonenumber}), name='telegram_setup'),
    # path('instructor/telegram_setup/', TelegramWizard.as_view([PhoneNumberForm, VerificationCodeForm]), name='telegram_setup'),
    path('instructor/telegram_setup/', views.configureDB_telegram, name='telegram_setup'),
    path('join/', PhoneNumberFormView.as_view(), name='phone_number_form'),
    path('csv/clt_file', views.clt_file_download),
    path('admin/csv/clt_file.csv', views.clt_file_ouput, name = "clt_file"),
    path('celery/trailhead/refresh', views.trailhead_refresh, name = 'trailhead_refresh'),
    #trailmixes
    path('instructor/trailmix/',views.trailhead_list,name='trailhead_list'),
    path('instructor/trailmix/create/', views.trailhead_create, name='trailhead_create'),
    path('instructor/trailmix/<str:pk>/delete/', views.trailhead_delete, name='trailhead_delete'),
]

CLE/templates/dataforms/trailmixes/partial_trailhead_create.html
<form method="post" action="{% url 'TMmod:trailhead_create' %}" class="js-trailhead-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Insert Trailmixes</h4>
    <button type="button" class="close" id="close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'dataforms/trailmixes/partial_trailhead_form.html' %}
  </div>
  <div class="modal-footer">
    <!-- <button type="button" class="btn btn-default" id="close">Close</button> -->
    <br>
    <button type="submit" class="btn btn-primary">Add Trailmix</button>
  </div>
</form>


<script>
  $('#close').on('click',function() {
    $('#modal-trailhead').modal('hide');
  });
</script>

CLE/templates/dataforms/trailmixes/partial_trailhead_delete.html
<form method="post" action="{% url 'TMmod:trailhead_delete' pk=trailhead.id %}" class="js-trailhead-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm Trailmix deletion</h4>
    <button type="button" class="close" id="close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the Trailmix? <strong>{{ trailhead.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <br>
    <button type="submit" class="btn btn-danger">Delete Trailmix</button>
  </div>
</form>

<script>
  $('#close').on('click',function() {
    $('#modal-trailhead').modal('hide');
  });
</script>

CLE/templates/dataforms/trailmixes/partial_trailhead_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

CLE/templates/dataforms/trailmixes/partial_trailhead_list.html
{% for trailhead in thm %}
  <tr>
      <td>{{ trailhead.name }}</td>
      <td> <a href={{ trailhead.link }}> {{ trailhead.link }} </a></td>
      <td>{{ trailhead.description }}</td>
      <td>{{ trailhead.badges }}</td>
      <td>{{ trailhead.course.course_title }}</td>
    <td style="width: 250px">
     
      <button type="button"
             class="btn btn-danger btn-sm js-delete-trailhead"
             data-url="{% url 'TMmod:trailhead_delete' pk=trailhead.id %}">
       <span class="glyphicon glyphicon-trash"></span> Delete
     </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No Trailmix</td>
  </tr>
{% endfor %}

CLE/templates/dataforms/trailmixes/trailhead_list.html
{% extends 'dataforms/dataformbase.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'js/dataforms/trailhead.js' %}"></script>
{% endblock %}

{% block content %}
  <!-- BUTTON TO TRIGGER THE ACTION -->
  <p>
    <button type="button"
            class="btn btn-primary js-create-trailhead"
            data-url="{% url 'TMmod:trailhead_create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New Trailmix
    </button>
  </p>

  <table class="table" id="trailhead-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Link</th>
        <th>Description</th>
        <th>Badges</th>
        <th>Course</th>
      </tr>
    </thead>
    <tbody>
        {% include 'dataforms/trailmixes/partial_trailhead_list.html' %}
    </tbody>
  </table>

  <!-- THE MODAL WE WILL BE USING -->
 <div class="modal fade" id="modal-trailhead">
   <div class="modal-dialog">
     <div class="modal-content">
     </div>
   </div>

 <script>
 $(document).ready(function() {
   console.log("{% url 'TMmod:trailhead_list' %} #trailhead-table")
    $("#trailhead-table").load("{% url 'TMmod:trailhead_list' %} #trailhead-table");
 });
 </script>


{% endblock %}